USE  Nissan
GO


CREATE VIEW SucursalPPP
AS
SELECT ROW_NUMBER() OVER (ORDER BY ID_SUCURSAL) AS INDICE, ID_SUCURSAL 
 FROM Distribuidor_o_sucursal 
GO
 
SELECT * FROM SucursalPPP
GO

CREATE VIEW VehiculoPPP
AS
SELECT ROW_NUMBER() OVER (ORDER BY ID_VEHICULO) AS INDICE, ID_VEHICULO 
 FROM VEHICULO 
GO

SELECT * FROM VehiculoPPP
GO


CREATE VIEW clientePPP
AS
SELECT ROW_NUMBER() OVER (ORDER BY ID_CLIENTE) AS INDICE, ID_CLIENTE 
 FROM CLIENTE 
GO

SELECT * FROM clientePPP
GO


/*DIMENSIONES VENTA COCHES*/
USE Nissan;
GO
/*
SELECT * FROM DISTRIBUIDOR_O_SUCURSAL as s INNER JOIN VENTA_VEHICULO vv ON s.ID_SUCURSAL=vv.FK_DISTRIBUIDORA
JOIN CLIENTE c ON c.ID_CLIENTE=vv.FK_CLIENTE JOIN VEHICULO v ON vv.FK_VEHICULO=v.ID_VEHICULO
*/
/*
SELECT v.ID_VEHICULO,s.ID_SUCURSAL,c.ID_CLIENTE,FECHA,ID_VENTA_VEHICULO FROM DISTRIBUIDOR_O_SUCURSAL as s INNER JOIN VENTA_VEHICULO vv ON s.ID_SUCURSAL=vv.FK_DISTRIBUIDORA
JOIN CLIENTE c ON c.ID_CLIENTE=vv.FK_CLIENTE JOIN VEHICULO v ON vv.FK_VEHICULO=v.ID_VEHICULO
*/

CREATE VIEW VENTAS_PPP
AS
SELECT ROW_NUMBER() OVER (ORDER BY ID_CLIENTE) AS INDICE, v.ID_VEHICULO,s.ID_SUCURSAL,c.ID_CLIENTE,FECHA,ID_VENTA_VEHICULO FROM DISTRIBUIDOR_O_SUCURSAL as s INNER JOIN VENTA_VEHICULO vv ON s.ID_SUCURSAL=vv.FK_DISTRIBUIDORA
JOIN CLIENTE c ON c.ID_CLIENTE=vv.FK_CLIENTE JOIN VEHICULO v ON vv.FK_VEHICULO=v.ID_VEHICULO
GO

SELECT * FROM VENTAS_PPP
GO



/*
SELECT * FROM 


*/

CREATE TABLE TABLA_HECHO_VENTAS_VEHICULO
(
ID_FECHA VARCHAR(15) NOT NULL,
ID_VEHICULO VARCHAR (15) NOT NULL,
ID_SUCURSAL VARCHAR(15) NOT NULL,
ID_CLIENTE VARCHAR(15) NOT NULL,
NUM_VENTA VARCHAR (30) NOT NULL
)

/*

DROP TABLE TABLA_HECHO_VENTAS_VEHICULO
DROP TABLE DIMENSION_SUCURSAL
DROP TABLE DIMENSION_VEHICULO
DROP TABLE DIMENSION_CLIENTE
DROP TABLE DIMENSION_FECHA
*/

--SELECT * FROM DISTRIBUIDOR_O_SUCURSAL

CREATE TABLE DIMENSION_SUCURSAL(
    ID_SUCURSAL VARCHAR(15) NOT NULL,
	DESCRIPCION VARCHAR (300) NULL,
	ESTADO VARCHAR(30) NOT NULL ,
	CIUDAD VARCHAR (100) NOT NULL ,
	PUNTUACION INT NULL
); 
GO

--SELECT * FROM VEHICULO
CREATE TABLE DIMENSION_VEHICULO (
	ID_VEHICULO VARCHAR (15)  NOT NULL,
	TIPO VARCHAR (300) NULL ,
	AÑO INT ,
	MODELO VARCHAR (300) NULL ,
	COLOR VARCHAR (200) NULL ,
	PRECIO MONEY NULL,
	ESTADO VARCHAR (20)
);
GO

CREATE TABLE DIMENSION_CLIENTE(
	ID_CLIENTE VARCHAR(15) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	PRIMER_APELLIDO VARCHAR(100) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(100) NULL,
	FECHA_NACIMIENTO DATE NULL,
	SEXO VARCHAR(1)
)
GO

CREATE TABLE DIMENSION_FECHA (
	ID_FECHA VARCHAR(15) NOT NULL ,
	DIA_DEL_MES INT NOT NULL,
	MES INT NOT NULL,
	AÑO INT NOT NULL,
	SEMANA_DEL_AÑO INT NOT NULL
);
GO





/****************************************************************************************************
ultima actualizacion: 09 DE SEPTIEBRE DE 2018 

RESTRICCIONES DE LLAVE PRIMARIA         PK                 *
*****************************************************************************************************/


ALTER TABLE DIMENSION_SUCURSAL  ADD 
	CONSTRAINT PK_SUCURSAL_DIMENSION_SUCURSAL 
	PRIMARY KEY  (ID_SUCURSAL); 
GO

ALTER TABLE DIMENSION_VEHICULO  ADD 
	CONSTRAINT PK_VEHICULO_DIMENSION_VEHICULO
	PRIMARY KEY  (ID_VEHICULO); 
GO
 

ALTER TABLE DIMENSION_CLIENTE  ADD 
	CONSTRAINT PK_DIMENSION_CLIENTE
	PRIMARY KEY  (ID_CLIENTE); 
GO

ALTER TABLE DIMENSION_FECHA  ADD 
	CONSTRAINT PK_FECHA_DIMENSION_FECHA
	PRIMARY KEY  (ID_FECHA); 
GO





/****************************************************************************************************
ultima actualizacion: 09 DE SEPTIEBRE DE 2018 
RESTRICCIONES DE LLAVE fORANEA         FK                 *
*****************************************************************************************************/


/*
CREATE TABLE TABLA_HECHO_VENTAS_VEHICULO(
ID_FECHA BIGINT NOT NULL,
ID_VEHICULO VARCHAR (15) NOT NULL,
ID_SUCURSAL VARCHAR(15) NOT NULL,
ID_CLIENTE VARCHAR(15) NOT NULL,
NUM_VENTA VARCHAR (30) NOT NULL)

*/




ALTER TABLE TABLA_HECHO_VENTAS_VEHICULO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_VEHICULO_DIMENSION_FECHA 
	FOREIGN KEY ( ID_FECHA )   
    REFERENCES DIMENSION_FECHA ( ID_FECHA  );
GO

ALTER TABLE TABLA_HECHO_VENTAS_VEHICULO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_VEHICULO_DIMENSION_VEHICULO 
	FOREIGN KEY ( ID_VEHICULO )   
    REFERENCES DIMENSION_VEHICULO ( ID_VEHICULO  );
GO

ALTER TABLE TABLA_HECHO_VENTAS_VEHICULO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_VEHICULO_DIMENSION_SUCURSAL 
	FOREIGN KEY ( ID_SUCURSAL )   
    REFERENCES DIMENSION_SUCURSAL ( ID_SUCURSAL  );
GO

ALTER TABLE TABLA_HECHO_VENTAS_VEHICULO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_VEHICULO_DIMENSION_CLIENTE 
	FOREIGN KEY ( ID_CLIENTE )   
    REFERENCES DIMENSION_CLIENTE ( ID_CLIENTE  );
GO







/*
PROCEDIMIENTO
*/


CREATE PROC SP_LLENA_DIMENSION_VEHICULO
  AS
     begin tran llena_dimension_vehiculo
	 DECLARE @ID_VEHICULO VARCHAR(15),  @TIPO VARCHAR(300), @AÑO INT, @MODELO VARCHAR(300), @COLOR VARCHAR(200), @PRECIO MONEY, @ESTADO VARCHAR(20),
	@cantidad_vechilos BIGINT,
      	
	 @CONT BIGINT = 1 , @CONT2 BIGINT=(SELECT COUNT(ID_VEHICULO) FROM VEHICULO)
	 
      
		
	 WHILE (@CONT <=  @CONT2)
        BEGIN 
           
	    SELECT  @ID_VEHICULO = ID_VEHICULO 
				FROM VEHICULOPPP
				WHERE INDICE = @CONT
				
				
				
		SELECT  @TIPO = TIPO 
				FROM VEHICULO
				WHERE ID_VEHICULO = @ID_VEHICULO
				
				SELECT  @AÑO = AÑO 
				FROM VEHICULO
				WHERE ID_VEHICULO = @ID_VEHICULO
				
				SELECT  @MODELO = MODELO 
				FROM VEHICULO
				WHERE ID_VEHICULO = @ID_VEHICULO
				
				SELECT  @COLOR = COLOR 
				FROM VEHICULO
				WHERE ID_VEHICULO = @ID_VEHICULO
				
				SELECT  @PRECIO = PRECIO 
				FROM VEHICULO
				WHERE ID_VEHICULO = @ID_VEHICULO
				
				SELECT  @ESTADO = ESTADO 
				FROM VEHICULO
				WHERE ID_VEHICULO = @ID_VEHICULO
				
				
				INSERT INTO DIMENSION_VEHICULO VALUES(@ID_VEHICULO,@TIPO,@AÑO,@MODELO,@COLOR,@PRECIO,@ESTADO);
		
		
        SET @CONT = @CONT + 1   
     END  -- FIN WHILE PRINC
  IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_dimension_vehiculo 
   END
  ELSE  
    COMMIT TRAN llena_dimension_vehiculo   
GO


--ejecucion
EXEC SP_LLENA_DIMENSION_VEHICULO


SELECT * FROM DIMENSION_VEHICULO





/***********************************************************************************************************************

*************************************************************************/



CREATE PROC SP_LLENA_DIMENSION_CLIENTE
  AS
     begin tran llena_dimension_cliente
	 DECLARE @ID_CLIENTE VARCHAR(15),  @NOMBRE VARCHAR(100),  @PRIMER_APELLIDO VARCHAR(100),  @SEGUNDO_APELLIDO VARCHAR(100), @FECHA_NACIMIENTO DATE, @SEXO VARCHAR(1),
	
      	
	 @CONT BIGINT = 1 , @CONT2 BIGINT=(SELECT COUNT(ID_CLIENTE) FROM CLIENTE)
	 
      
		
	 WHILE (@CONT <=  @CONT2)
        BEGIN 
           
	    SELECT  @ID_CLIENTE = ID_CLIENTE 
				FROM clientePPP
				WHERE INDICE = @CONT
				
				
		SELECT  @NOMBRE = NOMBRE 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
		SELECT  @PRIMER_APELLIDO = PRIMER_APELLIDO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
				SELECT  @SEGUNDO_APELLIDO = SEGUNDO_APELLIDO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
				SELECT  @FECHA_NACIMIENTO = FECHA_NACIMIENTO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
				SELECT  @SEXO = SEXO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
		
				
				
				INSERT INTO DIMENSION_CLIENTE VALUES(@ID_CLIENTE,@NOMBRE,@PRIMER_APELLIDO,@SEGUNDO_APELLIDO,@FECHA_NACIMIENTO,@SEXO);
		
		
        SET @CONT = @CONT + 1   
     END  -- FIN WHILE PRINC
  IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_dimension_cliente 
   END
  ELSE  
    COMMIT TRAN llena_dimension_cliente   
GO


--ejecucion
EXEC SP_LLENA_DIMENSION_CLIENTE


SELECT * FROM DIMENSION_CLIENTE





/***********************************************************************************************************************

*************************************************************************/



CREATE PROC SP_LLENA_DIMENSION_SUCURSAL
  AS
     begin tran llena_dimension_sucursal
	 DECLARE @ID_SUCURSAL VARCHAR(15),  @DESCRIPCION VARCHAR(300),  @ESTADO VARCHAR(30),  @CIUDAD VARCHAR(100), @PUNTUACION INT,
	
      	
	 @CONT BIGINT = 1 , @CONT2 BIGINT=(SELECT COUNT(ID_SUCURSAL) FROM DISTRIBUIDOR_O_SUCURSAL)
	 
      
		
	 WHILE (@CONT <=  @CONT2)
        BEGIN 
           
	    SELECT  @ID_SUCURSAL = ID_SUCURSAL 
				FROM sucursalppp
				WHERE INDICE = @CONT
				
				
		SELECT  @DESCRIPCION = DESCRIPCION
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				
				SELECT  @ESTADO = ESTADO
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				
				SELECT  @CIUDAD = CIUDAD
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				
				SELECT  @PUNTUACION = PUNTUACION
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				
				
		
				
				
				INSERT INTO DIMENSION_SUCURSAL VALUES(@ID_SUCURSAL,@DESCRIPCION,@ESTADO,@CIUDAD,@PUNTUACION);
		
		
        SET @CONT = @CONT + 1   
     END  -- FIN WHILE PRINC
  IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_dimension_sucursal 
   END
  ELSE  
    COMMIT TRAN llena_dimension_sucursal   
GO


--ejecucion
EXEC SP_LLENA_DIMENSION_SUCURSAL


SELECT * FROM DIMENSION_SUCURSAL

SELECT * FROM DISTRIBUIDOR_O_SUCURSAL
GO



/*




*********************************************************************************************************************/

CREATE PROC  SP_LLENA_TABLA_HECHO_VENTAS_VEHICULO

  AS
     begin tran llena_venta_vehiculo
	 DECLARE @ID_FECHA VARCHAR(15), @ID_SUCURSAL VARCHAR(15),@ID_CLIENTE VARCHAR(15), @ID_VEHICULO VARCHAR(15),@NUM_VENTA VARCHAR(30),@FECHA DATE,
	 @DIA_DEL_MES INT,@MES INT, @AÑO INT, @SEMANA_DEL_AÑO INT,
	 @CONT BIGINT = 1,  @N BIGINT=(SELECT COUNT(INDICE) FROM VENTAS_PPP)
      
      	
		
	 WHILE (@CONT <=  @N)
        BEGIN    
        SELECT  @ID_SUCURSAL = ID_SUCURSAL 
				FROM VENTAS_PPP
				WHERE INDICE = @CONT
				
				SELECT  @ID_VEHICULO = ID_VEHICULO
				FROM VENTAS_PPP
				WHERE INDICE = @CONT
				
				SELECT  @ID_CLIENTE = ID_CLIENTE 
				FROM VENTAS_PPP
				WHERE INDICE = @CONT
				
				SELECT  @NUM_VENTA = ID_VENTA_VEHICULO 
				FROM VENTAS_PPP
				WHERE INDICE = @CONT
				
				SELECT  @FECHA = FECHA 
				FROM VENTAS_PPP
				WHERE INDICE = @CONT
				
				
				SET @ID_FECHA= 'FEC' + CONVERT(VARCHAR,@CONT)
				
				SET @SEMANA_DEL_AÑO=DATEPART (ISO_WEEK,@FECHA)
					
					SET @DIA_DEL_MES=DATEPART (DAY,@FECHA)
					
					
					SET @MES=DATEPART (MONTH,@FECHA)
					
					SET @AÑO=DATEPART (YEAR,@FECHA)
					
					
					INSERT INTO DIMENSION_FECHA VALUES(@ID_FECHA,@DIA_DEL_MES,@MES,@AÑO,@SEMANA_DEL_AÑO)
					
					INSERT INTO TABLA_HECHO_VENTAS_VEHICULO VALUES (@ID_FECHA,@ID_VEHICULO,@ID_SUCURSAL,@ID_CLIENTE,@NUM_VENTA)
					
	   

        SET @CONT = @CONT + 1   
        
     END  -- FIN WHILE PRINC
  IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_venta_vehiculo 
   END
  ELSE  
    COMMIT TRAN llena_venta_vehiculo   
GO







--ejecucion
EXEC SP_LLENA_TABLA_HECHO_VENTAS_VEHICULO
GO


--DELETE FROM TABLA_HECHO_VENTAS_VEHICULO
SELECT * FROM TABLA_HECHO_VENTAS_VEHICULO

--DELETE FROM DIMENSION_FECHA
SELECT * FROM DIMENSION_FECHA



