USE Nissan
GO

SELECT * FROM ALMACEN_EMPRESA
SELECT * FROM DISTRIBUIDOR_O_SUCURSAL
SELECT * FROM VEHICULO
SELECT * FROM SERVICIO
SELECT * FROM CLIENTE
SELECT * FROM FACTURA_ALMACEN
SELECT * FROM DET_FACTURA_ALMACEN

SELECT * FROM VENTA_VEHICULO
SELECT * FROM DET_VENTA_VEHICULO

SELECT * FROM VENTA_ACCESORIO
SELECT * FROM DET_VENTA_ACCESORIO

SELECT * FROM FACT_SERVICIO
SELECT * FROM DET_FACT_SERVICIO

