/****************************************************************************************************
* PROYECTO BASES DE DATOS AVANZADAS   ultima actualizacion: 09 DE SEPTIEBRE DE 2018   
								Inst. Tecnologico de Leon *
* Autores:  
			•	José Guadalupe de Jesús Cervera Barbosa
			•	Judá Alector Vallejo Herrera
			•	Luis Saul Ornelas Pérez
			•	Miguel Ángel Ramírez Lira

 
*****************************************************************************************************/
use master;    
 go 
--DROP DATABASE Nissan
--go
CREATE DATABASE Nissan; 
GO
use Nissan;
GO

CREATE TABLE ALMACEN_EMPRESA (
	ID_ALMACEN_EMPRESA VARCHAR (10)  NOT null,
	DESCRIPCION VARCHAR (10) NULL,
	ESTADO VARCHAR(30) NOT NULL ,
	CIUDAD VARCHAR (100) NOT NULL ,
	CP VARCHAR (5) NULL ,
	COLONIA VARCHAR (200) NULL ,
	CALLE VARCHAR (200) NULL ,
	NUM_INT VARCHAR (10) NULL
); 
GO

CREATE TABLE DISTRIBUIDOR_O_SUCURSAL(
    ID_SUCURSAL VARCHAR(10) NOT NULL,
	DESCRIPCION VARCHAR (10) NULL,
	ESTADO VARCHAR(30) NOT NULL ,
	CIUDAD VARCHAR (100) NOT NULL ,
	CP VARCHAR (5) NULL ,
	COLONIA VARCHAR (200) NULL ,
	CALLE VARCHAR (200) NULL ,
	NUM_INT VARCHAR (10) NULL,
	PUNTUACION INT NULL
); 
GO

CREATE TABLE VEHICULO (
	ID_VEHICULO VARCHAR (10)  NOT NULL,
	DECRIPCION VARCHAR (30) NULL ,
	TIPO VARCHAR (20) NULL ,
	AÑO VARCHAR(4) NULL ,
	MODELO VARCHAR (5) NULL ,
	COLOR VARCHAR (30) NULL ,
	PRECIO MONEY NULL, 
	EXISTENCIA TINYINT NULL,
	ESTADO VARCHAR
);
GO


CREATE TABLE ACCESORIO (
	ID_ACCESORIO VARCHAR (10)  NOT NULL,
	DECRIPCION VARCHAR (30) NOT NULL,
	PRECIO MONEY NOT NULL, 
	EXISTENCIA TINYINT NULL,
	ESTADO VARCHAR NULL
);
GO


CREATE TABLE CLIENTE(
	ID_CLIENTE VARCHAR(10) NOT NULL,
	NOMBRE VARCHAR(60) NOT NULL,
	PRIMER_APELLIDO VARCHAR(60) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(60) NULL,
	CURP VARCHAR(18) NULL,
	FECHA_NACIMIENTO DATE NULL,
	SEXO VARCHAR(1)NOT NULL
)
GO

CREATE TABLE SERVICIO(
	ID_SERVICIO VARCHAR(10) NOT NULL,
	DESCRIPCION VARCHAR(200) NOT NULL,
	PRECIO MONEY NULL
)
GO


CREATE TABLE FACTURA_ALMACEN (
	NO_PEDIDO VARCHAR (10)  NOT NULL,
	FK_ALMACEN VARCHAR (10)  NOT NULL,
	FECHA DATE NULL,
	DESCRIPCION VARCHAR(10) NULL 
);
GO


CREATE TABLE DET_FACTURA_ALMACEN (
	FK_PEDIDO VARCHAR (10)  NOT NULL,
	FK_VEHICULO VARCHAR (10)  NOT NULL,
	FK_DISTRIBUIDORA VARCHAR (10) NOT NULL
);
GO

CREATE TABLE VENTA_VEHICULO (
	ID_VENTA_VEHICULO VARCHAR (10)  NOT NULL,
	FK_DISTRIBUIDORA VARCHAR (10)  NOT NULL,
	FECHA DATE NULL,
	SUTTOTAL MONEY NULL ,
	TOTAL MONEY NULL ,
	FORMA_PAGO VARCHAR(10) NULL
);
GO


CREATE TABLE DET_VENTA_VEHICULO (
	FK_VENTA_VEHICULO VARCHAR (10)  NOT NULL,
	FK_VEHICULO VARCHAR (10)  NOT NULL,
	FK_CLIENTE VARCHAR (10) NOT NULL
);
GO


CREATE TABLE VENTA_ACCESORIO (
	ID_VENTA_ACCESORIO VARCHAR (10)  NOT NULL,
	FK_DISTRIBUIDORA VARCHAR (10)  NOT NULL,
	FECHA DATE NULL,
	SUTTOTAL MONEY NULL ,
	TOTAL MONEY NULL ,
	FORMA_PAGO VARCHAR(10) NULL
);
GO


CREATE TABLE DET_VENTA_ACCESORIO (
	FK_VENTA_ACCESORIO VARCHAR (10)  NOT NULL,
	FK_ACCESORIO VARCHAR (10)  NOT NULL,
	FK_CLIENTE VARCHAR (10) NOT NULL
);
GO


CREATE TABLE FACT_SERVICIO (
	ID_FACT_SERVICIO VARCHAR (10)  NOT NULL,
	FK_DISTRIBUIDORA VARCHAR (10)  NOT NULL,
	FECHA DATE NULL,
	SUTTOTAL MONEY NULL ,
	TOTAL MONEY NULL ,
	FORMA_PAGO VARCHAR(10) NULL
);
GO


CREATE TABLE DET_FACT_SERVICIO (
	FK_FACT_SERVICIO VARCHAR (10)  NOT NULL,
	FK_SERVICIO VARCHAR (10)  NOT NULL,
	FK_CLIENTE VARCHAR (10) NOT NULL,
	PUNTUACION INT
);
GO



/****************************************************************************************************
ultima actualizacion: 09 DE SEPTIEBRE DE 2018 

RESTRICCIONES DE LLAVE PRIMARIA         PK                 *
*****************************************************************************************************/
-----------------------------------
ALTER TABLE ALMACEN_EMPRESA  ADD 
	CONSTRAINT PK_ALMACEN_EMPRESA 
	PRIMARY KEY  (ID_ALMACEN_EMPRESA); 
GO

ALTER TABLE DISTRIBUIDOR_O_SUCURSAL  ADD 
	CONSTRAINT PK_DISTRIBUIDOR_O_SUCURSAL 
	PRIMARY KEY  (ID_SUCURSAL); 
GO

ALTER TABLE VEHICULO  ADD 
	CONSTRAINT PK_VEHICULO
	PRIMARY KEY  (ID_VEHICULO); 
GO
 
ALTER TABLE ACCESORIO  ADD 
	CONSTRAINT PK_ACCESORIO 
	PRIMARY KEY  (ID_ACCESORIO); 
GO

ALTER TABLE CLIENTE  ADD 
	CONSTRAINT PK_CLIENTE
	PRIMARY KEY  (ID_CLIENTE); 
GO

ALTER TABLE SERVICIO  ADD 
	CONSTRAINT PK_SERVICIO 
	PRIMARY KEY  (ID_SERVICIO); 
GO


ALTER TABLE FACTURA_ALMACEN  ADD 
	CONSTRAINT PK_FACTURA_ALMACEN
	PRIMARY KEY  (NO_PEDIDO); 
GO

ALTER TABLE VENTA_VEHICULO  ADD 
	CONSTRAINT PK_VENTA_VEHICULO
	PRIMARY KEY  (ID_VENTA_VEHICULO); 
GO

ALTER TABLE VENTA_ACCESORIO  ADD 
	CONSTRAINT PK_VENTA_ACCESORIO
	PRIMARY KEY  (ID_VENTA_ACCESORIO); 
GO

ALTER TABLE FACT_SERVICIO  ADD 
	CONSTRAINT PK_FACT_SERVICIO 
	PRIMARY KEY  (ID_FACT_SERVICIO); 
GO


ALTER TABLE DET_FACTURA_ALMACEN  ADD 
	CONSTRAINT PK_DET_FACTURA_ALMACEN
	PRIMARY KEY  (FK_PEDIDO, FK_VEHICULO, FK_DISTRIBUIDORA); 
GO


ALTER TABLE DET_VENTA_VEHICULO  ADD 
	CONSTRAINT PK_DET_VENTA_VEHICULO
	PRIMARY KEY   (FK_VENTA_VEHICULO, FK_VEHICULO, FK_CLIENTE); 
GO
	
ALTER TABLE DET_VENTA_ACCESORIO  ADD 
	CONSTRAINT PK_DET_VENTA_ACCESORIO
	PRIMARY KEY  CLUSTERED (FK_VENTA_ACCESORIO, FK_ACCESORIO, FK_CLIENTE); 
GO

ALTER TABLE DET_FACT_SERVICIO  ADD 
	CONSTRAINT PK_ET_FACT_SERVICIO 
	PRIMARY KEY  CLUSTERED (FK_FACT_SERVICIO, FK_SERVICIO, FK_CLIENTE); 
GO


/****************************************************************************************************
ultima actualizacion: 09 DE SEPTIEBRE DE 2018 
RESTRICCIONES DE LLAVE fORANEA         FK                 *
*****************************************************************************************************/

ALTER TABLE FACTURA_ALMACEN ADD        
	CONSTRAINT FK_FACTURA_ALMACEN_ALMACEN_EMPRESA 
	FOREIGN KEY ( NO_PEDIDO )   
    REFERENCES ALMACEN_EMPRESA( ID_ALMACEN_EMPRESA  );
GO


ALTER TABLE DET_FACTURA_ALMACEN ADD        
	CONSTRAINT FK_DET_FACTURA_ALMACEN_FACTURA_ALMACEN
	FOREIGN KEY ( FK_PEDIDO )   
    REFERENCES FACTURA_ALMACEN( NO_PEDIDO  );
GO

ALTER TABLE DET_FACTURA_ALMACEN ADD        
	CONSTRAINT FK_DET_FACTURA_ALMACEN_DISTRIBUIDORA
	FOREIGN KEY ( FK_DISTRIBUIDORA )   
    REFERENCES DISTRIBUIDOR_O_SUCURSAL( ID_SUCURSAL  );
GO

ALTER TABLE DET_FACTURA_ALMACEN ADD        
	CONSTRAINT FK_DET_FACTURA_ALMACEN_VEHICULO
	FOREIGN KEY ( FK_VEHICULO )   
    REFERENCES VEHICULO( ID_VEHICULO  );
GO











ALTER TABLE VENTA_VEHICULO ADD        
	CONSTRAINT FK_SUCURSAL_VENTA_VEHICULO
	FOREIGN KEY ( FK_DISTRIBUIDORA )   
    REFERENCES DISTRIBUIDOR_O_SUCURSAL( ID_SUCURSAL  );
GO

ALTER TABLE VENTA_ACCESORIO ADD        
	CONSTRAINT FK_SUCURSAL_VENTA_ACCESORIO
	FOREIGN KEY ( FK_DISTRIBUIDORA )   
    REFERENCES DISTRIBUIDOR_O_SUCURSAL( ID_SUCURSAL  );
GO

ALTER TABLE FACT_SERVICIO ADD        
	CONSTRAINT FK_SUCURSAL_FACT_SERVICIO
	FOREIGN KEY ( FK_DISTRIBUIDORA )   
    REFERENCES DISTRIBUIDOR_O_SUCURSAL( ID_SUCURSAL  );
GO



ALTER TABLE DET_FACT_SERVICIO ADD        
	CONSTRAINT FK_CLIENTE_DET_FACT_SERVICIO_SERVICIO
	FOREIGN KEY ( FK_SERVICIO )   
    REFERENCES SERVICIO( ID_SERVICIO  );
GO

ALTER TABLE DET_FACT_SERVICIO ADD        
	CONSTRAINT FK_CLIENTE_DET_FACT_SERVICIO_SERVICIO2
	FOREIGN KEY ( FK_FACT_SERVICIO )   
    REFERENCES FACT_SERVICIO( ID_FACT_SERVICIO  );
GO

ALTER TABLE DET_FACT_SERVICIO ADD        
	CONSTRAINT FK_CLIENTE_DET_FACT_SERVICIO_SERVICIO3
	FOREIGN KEY ( FK_CLIENTE )   
    REFERENCES CLIENTE( ID_CLIENTE  );
GO





ALTER TABLE DET_VENTA_ACCESORIO ADD        
	CONSTRAINT FK_CLIENTE_DET_VENTA_ACCESORIO_ACCESORIO
	FOREIGN KEY ( FK_ACCESORIO )   
    REFERENCES ACCESORIO( ID_ACCESORIO  );
GO

ALTER TABLE DET_VENTA_ACCESORIO ADD        
	CONSTRAINT FK_CLIENTE_DET_VENTA_ACCESORIO_ACCESORIO2
	FOREIGN KEY ( FK_VENTA_ACCESORIO)   
    REFERENCES VENTA_ACCESORIO( ID_VENTA_ACCESORIO  );
GO

ALTER TABLE DET_VENTA_ACCESORIO ADD        
	CONSTRAINT FK_CLIENTE_DET_VENTA_ACCESORIO_ACCESORIO3
	FOREIGN KEY ( FK_CLIENTE )   
    REFERENCES CLIENTE( ID_CLIENTE  );
GO


ALTER TABLE DET_VENTA_VEHICULO ADD        
	CONSTRAINT FK_CLIENTE_DET_VENTA_ACCESORIO_VEHICULO1
	FOREIGN KEY ( FK_VEHICULO )   
    REFERENCES VEHICULO( ID_VEHICULO  );
GO

ALTER TABLE DET_VENTA_VEHICULO ADD        
	CONSTRAINT FK_CLIENTE_DET_VENTA_ACCESORIO_AVEHICULO2
	FOREIGN KEY ( FK_VENTA_VEHICULO)   
    REFERENCES VENTA_VEHICULO( ID_VENTA_VEHICULO  );
GO

ALTER TABLE DET_VENTA_VEHICULO ADD        
	CONSTRAINT FK_CLIENTE_DET_VENTA_ACCESORIO_VEHICULO3
	FOREIGN KEY ( FK_CLIENTE )   
    REFERENCES CLIENTE( ID_CLIENTE  );
GO





/*******************************RESTRICCION UNIQUE**************************/
ALTER TABLE CLIENTE
ADD CONSTRAINT UX_curp
UNIQUE NONCLUSTERED (CURP)
GO




/******************************1. Restricciones de dominio: DEFAULT*****************************/
/*valor por defecto para sexo es 'M' (masculino), 'F'(Femenino) insertarlo*/
create default df_sexo
as 'M'
go
exec sp_bindefault 'df_sexo', 'CLIENTE.SEXO'--variable sexo de persona, tome la variable df_sexo
go

/*valor por defecto para municipio es Leon*/
create default df_ciudad
as 'León'
go
exec sp_bindefault 'df_municipio', 'DISTRIBUIDOR_O_SUCURSAL.CIUDAD'
go
exec sp_bindefault 'df_municipio', 'DISTRIBUIDOR_O_SUCURSAL.CIUDAD'
go

/*valor por defecto para municipio es Guanajuato*/
create default df_estado
as 'Guanajuato'
go
exec sp_bindefault 'df_estado', 'DISTRIBUIDOR_O_SUCURSAL.estado'
go
exec sp_bindefault 'df_estado', 'DISTRIBUIDOR_O_SUCURSAL.estado'
go


/*************************************************2. RESTRICCIONES DE DOMINIO:  RULES****************/
/*REGLA: solo admite en atributo sexo de la tabla persona M -> masculino  y una F- > femenino*/
create rule rl_sexo
as 
	@mivariable = 'M' or @mivariable ='F'
	--otra forma cuando son muchas @mivar IN('M','F')
Go 
EXEC sp_bindrule 'rl_sexo','CLIENTE.sexo'
go

create rule rl_cp
as --char (5)
	@cp LIKE('[0-9][0-9][0-9][0-9][0-9]')--Primer caracter es numero, el seguno igual, asi hasta el quinto
go
exec sp_bindrule 'rl_cp','DISTRIBUIDOR_O_SUCURSAL.cp'
exec sp_bindrule 'rl_cp','DISTRIBUIDOR_O_SUCURSAL.cp'
GO

create rule rl_curp as
--like compara cadenas
	@curp LIKE
	('[a-z][a-z][a-z][a-z][0-9][0-9][0-9][0-9][0-9][0-9][HM][a-z][a-z][a-z][a-z][a-z][0-9][0-9]')
go
exec sp_bindrule'rl_curp','CLIENTE.curp'
go


/**************************************3. Restricciones de dominio: CHECK*********************/
/*Restriccion CHECK: las fechas finales deben ser mayores a las fechas de inicio*/
/*
ALTER TABLE CLIENTE
ADD CONSTRAINT 
check_curp CHECK
	(curp LIKE '[a-z][a-z][a-z][a-z][0-9][0-9][0-9][0-9][0-9][0-9][HM][a-z][a-z][a-z][a-z][a-z][0-9][0-9]')
go
*/





























































































