USE  Nissan
GO


CREATE VIEW SucursalPPPs
AS
SELECT ROW_NUMBER() OVER (ORDER BY ID_SUCURSAL) AS INDICE, ID_SUCURSAL 
 FROM Distribuidor_o_sucursal 
GO
 
SELECT * FROM SucursalPPPs
GO

CREATE VIEW ServicioPPPs
AS
SELECT ROW_NUMBER() OVER (ORDER BY ID_SERVICIO) AS INDICE, ID_SERVICIO
 FROM SERVICIO
GO

SELECT * FROM ServicioPPPs
GO

CREATE VIEW clientePPPs
AS
SELECT ROW_NUMBER() OVER (ORDER BY ID_CLIENTE) AS INDICE, ID_CLIENTE 
 FROM CLIENTE 
GO

SELECT * FROM clientePPPs
GO

/*DIMENSIONES VENTA SERVICIOS*/
USE Nissan;
GO
/*
SELECT * FROM DISTRIBUIDOR_O_SUCURSAL as s INNER JOIN FACT_SERVICIO ser ON ser.FK_DISTRIBUIDORA = s.ID_SUCURSAL
JOIN CLIENTE c ON c.ID_CLIENTE = ser.FK_CLIENTE JOIN DET_FACT_SERVICIO det_ser ON ser.ID_FACT_SERVICIO = det_ser.FK_FACT_SERVICIO JOIN SERVICIO se ON det_ser.FK_SERVICIO = se.ID_SERVICIO
*/
/*
SELECT se.ID_SERVICIO, s.ID_SUCURSAL, c.ID_CLIENTE, FECHA, ser.ID_FACT_SERVICIO  FROM DISTRIBUIDOR_O_SUCURSAL as s INNER JOIN FACT_SERVICIO ser ON ser.FK_DISTRIBUIDORA = s.ID_SUCURSAL
JOIN CLIENTE c ON c.ID_CLIENTE = ser.FK_CLIENTE JOIN DET_FACT_SERVICIO det_ser ON ser.ID_FACT_SERVICIO = det_ser.FK_FACT_SERVICIO JOIN SERVICIO se ON det_ser.FK_SERVICIO = se.ID_SERVICIO
*/

CREATE VIEW VENTAS_SERVICIO_PPPs
AS
SELECT ROW_NUMBER() OVER (ORDER BY c.ID_CLIENTE) AS INDICE,
se.ID_SERVICIO, s.ID_SUCURSAL, c.ID_CLIENTE, FECHA, ser.ID_FACT_SERVICIO, det_ser.PUNTUACION   FROM DISTRIBUIDOR_O_SUCURSAL as s INNER JOIN FACT_SERVICIO ser ON ser.FK_DISTRIBUIDORA = s.ID_SUCURSAL
JOIN CLIENTE c ON c.ID_CLIENTE = ser.FK_CLIENTE JOIN DET_FACT_SERVICIO det_ser ON ser.ID_FACT_SERVICIO = det_ser.FK_FACT_SERVICIO JOIN SERVICIO se ON det_ser.FK_SERVICIO = se.ID_SERVICIO
GO
/*
SELECT * FROM VENTAS_SERVICIO_PPPs
GO
*/

--DROP TABLE TABLA_HECHO_VENTAS_SERVICIO
CREATE TABLE TABLA_HECHO_VENTAS_SERVICIO
(
ID_FECHA VARCHAR(15) NOT NULL,
ID_SERVICIO VARCHAR (15) NOT NULL,
ID_SUCURSAL VARCHAR(15) NOT NULL,
ID_CLIENTE VARCHAR(15) NOT NULL,
PUNTUACION INT NOT NULL,
NUM_FACT VARCHAR (30) NOT NULL
);
GO

/*

DROP TABLE TABLA_HECHO_VENTAS_SERVICIO
DROP TABLE DIMENSION_SUCURSAL_S
DROP TABLE DIMENSION_SERVICIO_S
DROP TABLE DIMENSION_CLIENTE_S
DROP TABLE DIMENSION_FECHA_S
*/

/*

DELETE FROM TABLA_HECHO_VENTAS_SERVICIO
DELETE FROM DIMENSION_SUCURSAL_S
DELETE FROM DIMENSION_SERVICIO_S
DELETE FROM DIMENSION_CLIENTE_S
DELETE FROM DIMENSION_FECHA_S
*/



--SELECT * FROM DISTRIBUIDOR_O_SUCURSAL

CREATE TABLE DIMENSION_SUCURSAL_S(
    ID_SUCURSAL VARCHAR(15) NOT NULL,
	DESCRIPCION VARCHAR (300) NULL,
	ESTADO VARCHAR(30) NOT NULL ,
	CIUDAD VARCHAR (100) NOT NULL ,
	PUNTUACION INT NULL
); 
GO

--SELECT * FROM VEHICULO
--DROP  TABLE DIMENSION_SERVICIO_S
CREATE TABLE DIMENSION_SERVICIO_S (
	ID_SERVICIO VARCHAR (15)  NOT NULL,
	DESCRIPCION VARCHAR (500) NOT NULL,
	PRECIO MONEY NULL
);
GO

CREATE TABLE DIMENSION_CLIENTE_S(
	ID_CLIENTE VARCHAR(15) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	PRIMER_APELLIDO VARCHAR(100) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(100) NULL,
	FECHA_NACIMIENTO DATE NULL,
	SEXO VARCHAR(1)
)
GO

CREATE TABLE DIMENSION_FECHA_S (
	ID_FECHA VARCHAR(15) NOT NULL ,
	DIA_DEL_MES INT NOT NULL,
	MES INT NOT NULL,
	AÑO INT NOT NULL,
	SEMANA_DEL_AÑO INT NOT NULL
);
GO



/*****************************************************************

RESTRICCIONES DE LLAVE PRIMARIA
******************************************************************/

ALTER TABLE DIMENSION_SUCURSAL_S  ADD 
	CONSTRAINT PK_SUCURSAL_DIMENSION_SUCURSAL_S 
	PRIMARY KEY  (ID_SUCURSAL); 
GO

ALTER TABLE DIMENSION_SERVICIO_S  ADD 
	CONSTRAINT PK_VEHICULO_DIMENSION_SERVICIO_S
	PRIMARY KEY  (ID_SERVICIO); 
GO
 

ALTER TABLE DIMENSION_CLIENTE_S  ADD 
	CONSTRAINT PK_DIMENSION_CLIENTE_S
	PRIMARY KEY  (ID_CLIENTE); 
GO

ALTER TABLE DIMENSION_FECHA_S  ADD 
	CONSTRAINT PK_FECHA_DIMENSION_FECHA_S
	PRIMARY KEY  (ID_FECHA); 
GO

/*****************************************************************

RESTRICCIONES DE LLAVE FORANEA
******************************************************************/

ALTER TABLE TABLA_HECHO_VENTAS_SERVICIO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_SERVICIO_DIMENSION_FECHA 
	FOREIGN KEY ( ID_FECHA )   
    REFERENCES DIMENSION_FECHA_S ( ID_FECHA  );
GO

ALTER TABLE TABLA_HECHO_VENTAS_SERVICIO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_SERVICIO_DIMENSION_SERVICIO 
	FOREIGN KEY ( ID_SERVICIO )   
    REFERENCES DIMENSION_SERVICIO_S ( ID_SERVICIO  );
GO

ALTER TABLE TABLA_HECHO_VENTAS_SERVICIO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_SERVICIO_DIMENSION_SUCURSAL 
	FOREIGN KEY ( ID_SUCURSAL )   
    REFERENCES DIMENSION_SUCURSAL_S ( ID_SUCURSAL  );
GO

ALTER TABLE TABLA_HECHO_VENTAS_SERVICIO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_SERVICIO_DIMENSION_CLIENTE 
	FOREIGN KEY ( ID_CLIENTE )   
    REFERENCES DIMENSION_CLIENTE_S ( ID_CLIENTE  );
GO

/*
PROCEDIMIENTO
*/


CREATE PROC SP_LLENA_DIMENSION_SERVICIO
  AS
     begin tran llena_dimension_servicio
	 DECLARE @ID_SERVICIO VARCHAR(15), @DESCRIPCION VARCHAR (500), @PRECIO MONEY,
	@cantidad_servicios BIGINT,
      	
	 @CONT BIGINT = 1 , @CONT2 BIGINT=(SELECT COUNT(ID_SERVICIO) FROM SERVICIO)
	 
      
		
	 WHILE (@CONT <=  @CONT2)
        BEGIN 
           
	    SELECT  @ID_SERVICIO = ID_SERVICIO 
				FROM ServicioPPPs
				WHERE INDICE = @CONT
				
				
		SELECT  @DESCRIPCION = DESCRIPCION
				FROM SERVICIO
				WHERE ID_SERVICIO = @ID_SERVICIO
				
		SELECT  @PRECIO = PRECIO
				FROM SERVICIO
				WHERE ID_SERVICIO = @ID_SERVICIO
				
				INSERT INTO DIMENSION_SERVICIO_S VALUES(@ID_SERVICIO,@DESCRIPCION,@PRECIO);
		
		
        SET @CONT = @CONT + 1   
     END  -- FIN WHILE PRINC
  IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_dimension_servicio 
   END
  ELSE  
    COMMIT TRAN llena_dimension_servicio   
GO

EXEC SP_LLENA_DIMENSION_SERVICIO
GO
/*
SELECT * FROM DIMENSION_SERVICIO_S
GO
*/
/*Lenar dimencion de cliente*/

CREATE PROC SP_LLENA_DIMENSION_CLIENTE_S
  AS
     begin tran llena_dimension_cliente_s
	 DECLARE @ID_CLIENTE VARCHAR(15),  @NOMBRE VARCHAR(100),  @PRIMER_APELLIDO VARCHAR(100),  @SEGUNDO_APELLIDO VARCHAR(100), @FECHA_NACIMIENTO DATE, @SEXO VARCHAR(1),
	
      	
	 @CONT BIGINT = 1 , @CONT2 BIGINT=(SELECT COUNT(ID_CLIENTE) FROM CLIENTE)
	 
      
		
	 WHILE (@CONT <=  @CONT2)
        BEGIN 
           
	    SELECT  @ID_CLIENTE = ID_CLIENTE 
				FROM clientePPPs
				WHERE INDICE = @CONT
				
				
		SELECT  @NOMBRE = NOMBRE 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
		SELECT  @PRIMER_APELLIDO = PRIMER_APELLIDO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
		SELECT  @SEGUNDO_APELLIDO = SEGUNDO_APELLIDO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
		SELECT  @FECHA_NACIMIENTO = FECHA_NACIMIENTO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
		SELECT  @SEXO = SEXO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
		INSERT INTO DIMENSION_CLIENTE_S VALUES(@ID_CLIENTE,@NOMBRE,@PRIMER_APELLIDO,@SEGUNDO_APELLIDO,@FECHA_NACIMIENTO,@SEXO);
		
		
        SET @CONT = @CONT + 1   
     END  -- FIN WHILE PRINC
  IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_dimension_cliente_s
   END
  ELSE  
    COMMIT TRAN llena_dimension_cliente_s 
GO


--ejecucion
EXEC SP_LLENA_DIMENSION_CLIENTE_S

/*
SELECT * FROM DIMENSION_CLIENTE_S
GO
*/



/***********************************************************************************************************************

*************************************************************************/



CREATE PROC SP_LLENA_DIMENSION_SUCURSAL_S
  AS
     begin tran llena_dimension_sucursal_s
	 DECLARE @ID_SUCURSAL VARCHAR(15),  @DESCRIPCION VARCHAR(300),  @ESTADO VARCHAR(30),  @CIUDAD VARCHAR(100), @PUNTUACION INT,
	
	 @CONT BIGINT = 1 , @CONT2 BIGINT=(SELECT COUNT(ID_SUCURSAL) FROM DISTRIBUIDOR_O_SUCURSAL)
	 
	 WHILE (@CONT <=  @CONT2)
        BEGIN 
           
	    SELECT  @ID_SUCURSAL = ID_SUCURSAL 
				FROM sucursalppps
				WHERE INDICE = @CONT
				
				
		SELECT  @DESCRIPCION = DESCRIPCION
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				
		SELECT  @ESTADO = ESTADO
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				
		SELECT  @CIUDAD = CIUDAD
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				
		SELECT  @PUNTUACION = PUNTUACION
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				
		
		INSERT INTO DIMENSION_SUCURSAL_S VALUES(@ID_SUCURSAL,@DESCRIPCION,@ESTADO,@CIUDAD,@PUNTUACION);
		
		
        SET @CONT = @CONT + 1   
     END  -- FIN WHILE PRINC
  IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_dimension_sucursal_s 
   END
  ELSE  
    COMMIT TRAN llena_dimension_sucursal_s   
GO


--ejecucion
EXEC SP_LLENA_DIMENSION_SUCURSAL_S
GO

--SELECT * FROM DIMENSION_SUCURSAL_S

--SELECT * FROM DISTRIBUIDOR_O_SUCURSAL
--GO

/*




*********************************************************************************************************************/

CREATE PROC  SP_LLENA_TABLA_HECHO_VENTAS_SERVICIO
  AS
     begin tran llena_venta_servicio
	 DECLARE @ID_FECHA VARCHAR(15), @ID_SUCURSAL VARCHAR(15),@ID_CLIENTE VARCHAR(15), @ID_SERVICIO VARCHAR(15),@NUM_FACT VARCHAR(30), @PUNTUACION INT,@FECHA DATE,
	 @DIA_DEL_MES INT,@MES INT, @AÑO INT, @SEMANA_DEL_AÑO INT,
	 @CONT BIGINT = 1,  @N BIGINT=(SELECT COUNT(INDICE) FROM VENTAS_SERVICIO_PPPs)
      
      	
		
	 WHILE (@CONT <=  @N)
        BEGIN    
        SELECT  @ID_SUCURSAL = ID_SUCURSAL 
				FROM VENTAS_SERVICIO_PPPs
				WHERE INDICE = @CONT
				
		SELECT  @ID_SERVICIO = ID_SERVICIO
				FROM VENTAS_SERVICIO_PPPs
				WHERE INDICE = @CONT
				
		SELECT  @ID_CLIENTE = ID_CLIENTE 
				FROM VENTAS_SERVICIO_PPPs
				WHERE INDICE = @CONT
				
		SELECT  @NUM_FACT = ID_FACT_SERVICIO
				FROM VENTAS_SERVICIO_PPPs
				WHERE INDICE = @CONT
				
		SELECT @PUNTUACION = PUNTUACION
				FROM VENTAS_SERVICIO_PPPs
				WHERE INDICE = @CONT
				
		SELECT  @FECHA = FECHA 
				FROM VENTAS_SERVICIO_PPPs
				WHERE INDICE = @CONT
				
				
		SET @ID_FECHA= 'FEC' + CONVERT(VARCHAR,@CONT)
				
		SET @SEMANA_DEL_AÑO=DATEPART (ISO_WEEK,@FECHA)
					
		SET @DIA_DEL_MES=DATEPART (DAY,@FECHA)
					
					
		SET @MES=DATEPART (MONTH,@FECHA)
					
		SET @AÑO=DATEPART (YEAR,@FECHA)
					
					
		INSERT INTO DIMENSION_FECHA_S VALUES(@ID_FECHA,@DIA_DEL_MES,@MES,@AÑO,@SEMANA_DEL_AÑO)
					
		INSERT INTO TABLA_HECHO_VENTAS_SERVICIO VALUES (@ID_FECHA,@ID_SERVICIO,@ID_SUCURSAL,@ID_CLIENTE,@PUNTUACION,@NUM_FACT)
					
	   

        SET @CONT = @CONT + 1   
        
     END  -- FIN WHILE PRINC
  IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_venta_servicio 
   END
  ELSE  
    COMMIT TRAN llena_venta_servicio   
GO







--ejecucion
EXEC SP_LLENA_TABLA_HECHO_VENTAS_SERVICIO
GO


--DELETE FROM TABLA_HECHO_VENTAS_VEHICULO
/*
SELECT * FROM TABLA_HECHO_VENTAS_SERVICIO
GO
*/
--DELETE FROM DIMENSION_FECHA
/*
SELECT * FROM DIMENSION_FECHA_S
GO
*/