/****************************************************************************************************
* PROYECTO BASES DE DATOS AVANZADAS   ultima actualizacion: 09 DE SEPTIEBRE DE 2018   
								Inst. Tecnologico de Leon *
* Autores:  
			•	José Guadalupe de Jesús Cervera Barbosa
			•	Judá Alector Vallejo Herrera
			•	Luis Saul Ornelas Pérez
			•	Miguel Ángel Ramírez Lira

 
*****************************************************************************************************/
--Nota, todas los requerimientos deben ser una transaccion 





use master;    
 go 
--DROP DATABASE Nissan
--go
CREATE DATABASE Nissan; 
GO
use Nissan;
GO

--SELECT * FROM ALMACEN_EMPRESA
CREATE TABLE ALMACEN_EMPRESA (
	ID_ALMACEN_EMPRESA VARCHAR (15)  NOT null,
	DESCRIPCION VARCHAR (300) NULL,
	ESTADO VARCHAR(30) NOT NULL ,
	CIUDAD VARCHAR (100) NOT NULL ,
	CP VARCHAR (5) NULL ,
	COLONIA VARCHAR (200) NULL ,
	CALLE VARCHAR (200) NULL ,
	NUM_INT VARCHAR (10) NULL
); 
GO

--SELECT * FROM DISTRIBUIDOR_O_SUCURSAL
CREATE TABLE DISTRIBUIDOR_O_SUCURSAL(
    ID_SUCURSAL VARCHAR(15) NOT NULL,
	DESCRIPCION VARCHAR (300) NULL,
	ESTADO VARCHAR(30) NOT NULL ,
	CIUDAD VARCHAR (100) NOT NULL ,
	CP VARCHAR (5) NULL ,
	COLONIA VARCHAR (200) NULL ,
	CALLE VARCHAR (200) NULL ,
	NUM_INT VARCHAR (10) NULL,
	PUNTUACION INT NULL
); 
GO

--SELECT * FROM VEHICULO
CREATE TABLE VEHICULO (
	ID_VEHICULO VARCHAR (15)  NOT NULL,
	DECRIPCION VARCHAR (300) NULL ,
	TIPO VARCHAR (300) NULL ,
	AÑO INT ,
	MODELO VARCHAR (300) NULL ,
	COLOR VARCHAR (200) NULL ,
	PRECIO MONEY NULL,
	ESTADO VARCHAR (20)
);
GO

--SELECT * FROM ACCESORIO
CREATE TABLE ACCESORIO (
	ID_ACCESORIO VARCHAR (15)  NOT NULL,
	DECRIPCION VARCHAR (200) NOT NULL,
	PRECIO MONEY NOT NULL, 
	EXISTENCIA int NULL
);
GO


CREATE TABLE CLIENTE(
	ID_CLIENTE VARCHAR(15) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	PRIMER_APELLIDO VARCHAR(100) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(100) NULL,
	CURP VARCHAR(20) NULL,--debe ser de 18
	FECHA_NACIMIENTO DATE NULL,
	SEXO VARCHAR(1) NULL
)
GO


CREATE TABLE SERVICIO(
	ID_SERVICIO VARCHAR(15) NOT NULL,
	DESCRIPCION VARCHAR(500) NOT NULL,
	PRECIO MONEY NULL
)
GO

--DROP TABLE FACTURA_ALMACEN
CREATE TABLE FACTURA_ALMACEN (
	NO_PEDIDO VARCHAR (30)  NOT NULL,
	FK_ALMACEN VARCHAR (15)  NOT NULL,
	FK_DISTRIBUIDORA VARCHAR (15) NOT NULL,
	FECHA DATE NULL,
	DESCRIPCION VARCHAR(10) NULL 
);
GO

--DROP TABLE DET_FACTURA_ALMACEN
CREATE TABLE DET_FACTURA_ALMACEN (
	FK_PEDIDO VARCHAR (30)  NOT NULL,
	FK_VEHICULO VARCHAR (15)  NOT NULL
);
GO

CREATE TABLE VENTA_VEHICULO (
	ID_VENTA_VEHICULO VARCHAR (30)  NOT NULL,
	FK_DISTRIBUIDORA VARCHAR (15)  NOT NULL,
	FK_CLIENTE VARCHAR (15) NOT NULL,
	FK_VEHICULO VARCHAR (15)  NOT NULL,
	FECHA DATE NULL,
	FORMA_PAGO VARCHAR(10) NULL
);
GO


CREATE TABLE VENTA_ACCESORIO (
	ID_VENTA_ACCESORIO VARCHAR (30)  NOT NULL,
	FK_DISTRIBUIDORA VARCHAR (15)  NOT NULL,
	FK_CLIENTE VARCHAR (15) NOT NULL,
	FECHA DATE NULL,
	FORMA_PAGO VARCHAR(10) NULL
);
GO


CREATE TABLE DET_VENTA_ACCESORIO (
	FK_VENTA_ACCESORIO VARCHAR (30)  NOT NULL,
	FK_ACCESORIO VARCHAR (15)  NOT NULL,
	CANTIDAD INT
);
GO


CREATE TABLE FACT_SERVICIO (
	ID_FACT_SERVICIO VARCHAR (30)  NOT NULL,
	FK_DISTRIBUIDORA VARCHAR (15)  NOT NULL,
	FK_CLIENTE VARCHAR (15) NOT NULL,
	FECHA DATE NULL,
	FORMA_PAGO VARCHAR(10) NULL
);
GO


CREATE TABLE DET_FACT_SERVICIO (
	FK_FACT_SERVICIO VARCHAR (30)  NOT NULL,
	FK_SERVICIO VARCHAR (15)  NOT NULL,
	PUNTUACION INT
);
GO



/****************************************************************************************************
ultima actualizacion: 09 DE SEPTIEBRE DE 2018 

RESTRICCIONES DE LLAVE PRIMARIA         PK                 *
*****************************************************************************************************/
-----------------------------------
ALTER TABLE ALMACEN_EMPRESA  ADD 
	CONSTRAINT PK_ALMACEN_EMPRESA 
	PRIMARY KEY  (ID_ALMACEN_EMPRESA); 
GO

ALTER TABLE DISTRIBUIDOR_O_SUCURSAL  ADD 
	CONSTRAINT PK_DISTRIBUIDOR_O_SUCURSAL 
	PRIMARY KEY  (ID_SUCURSAL); 
GO

ALTER TABLE VEHICULO  ADD 
	CONSTRAINT PK_VEHICULO
	PRIMARY KEY  (ID_VEHICULO); 
GO
 
ALTER TABLE ACCESORIO  ADD 
	CONSTRAINT PK_ACCESORIO 
	PRIMARY KEY  (ID_ACCESORIO); 
GO

ALTER TABLE CLIENTE  ADD 
	CONSTRAINT PK_CLIENTE
	PRIMARY KEY  (ID_CLIENTE); 
GO

ALTER TABLE SERVICIO  ADD 
	CONSTRAINT PK_SERVICIO 
	PRIMARY KEY  (ID_SERVICIO); 
GO


ALTER TABLE FACTURA_ALMACEN  ADD 
	CONSTRAINT PK_FACTURA_ALMACEN
	PRIMARY KEY  (NO_PEDIDO); 
GO

ALTER TABLE VENTA_VEHICULO  ADD 
	CONSTRAINT PK_VENTA_VEHICULO
	PRIMARY KEY  (ID_VENTA_VEHICULO); 
GO

ALTER TABLE VENTA_ACCESORIO  ADD 
	CONSTRAINT PK_VENTA_ACCESORIO
	PRIMARY KEY  (ID_VENTA_ACCESORIO); 
GO

ALTER TABLE FACT_SERVICIO  ADD 
	CONSTRAINT PK_FACT_SERVICIO 
	PRIMARY KEY  (ID_FACT_SERVICIO); 
GO


ALTER TABLE DET_FACTURA_ALMACEN  ADD 
	CONSTRAINT PK_DET_FACTURA_ALMACEN
	PRIMARY KEY  (FK_PEDIDO, FK_VEHICULO); 
GO

	
ALTER TABLE DET_VENTA_ACCESORIO  ADD 
	CONSTRAINT PK_DET_VENTA_ACCESORIO
	PRIMARY KEY  CLUSTERED (FK_VENTA_ACCESORIO, FK_ACCESORIO); 
GO

ALTER TABLE DET_FACT_SERVICIO  ADD 
	CONSTRAINT PK_ET_FACT_SERVICIO 
	PRIMARY KEY  CLUSTERED (FK_FACT_SERVICIO, FK_SERVICIO); 
GO


/****************************************************************************************************
ultima actualizacion: 09 DE SEPTIEBRE DE 2018 
RESTRICCIONES DE LLAVE fORANEA         FK                 *
*****************************************************************************************************/

ALTER TABLE FACTURA_ALMACEN ADD        
	CONSTRAINT FK_FACTURA_ALMACEN_ALMACEN_EMPRESA 
	FOREIGN KEY ( FK_ALMACEN )   
    REFERENCES ALMACEN_EMPRESA ( ID_ALMACEN_EMPRESA  );
GO

ALTER TABLE FACTURA_ALMACEN ADD        
	CONSTRAINT FK_FACTURA_ALMACEN_SUCURSAL
	FOREIGN KEY ( FK_DISTRIBUIDORA )   
    REFERENCES DISTRIBUIDOR_O_SUCURSAL ( ID_SUCURSAL  );
GO


ALTER TABLE DET_FACTURA_ALMACEN ADD        
	CONSTRAINT FK_DET_FACTURA_ALMACEN_FACTURA_ALMACEN
	FOREIGN KEY ( FK_PEDIDO )   
    REFERENCES FACTURA_ALMACEN( NO_PEDIDO  );
GO

ALTER TABLE DET_FACTURA_ALMACEN ADD        
	CONSTRAINT FK_DET_FACTURA_ALMACEN_VEHICULO
	FOREIGN KEY ( FK_VEHICULO )   
    REFERENCES VEHICULO( ID_VEHICULO  );
GO


ALTER TABLE VENTA_VEHICULO ADD        
	CONSTRAINT FK_SUCURSAL_VENTA_VEHICULO
	FOREIGN KEY ( FK_DISTRIBUIDORA )   
    REFERENCES DISTRIBUIDOR_O_SUCURSAL( ID_SUCURSAL  );
GO
ALTER TABLE VENTA_VEHICULO ADD        
	CONSTRAINT FK_CLIENTE_VENTA_VEHICULO
	FOREIGN KEY ( FK_CLIENTE )   
    REFERENCES CLIENTE( ID_CLIENTE  );
GO

ALTER TABLE VENTA_VEHICULO ADD        
	CONSTRAINT FK_VEHICULO_VENTA_VEHICULO
	FOREIGN KEY ( FK_VEHICULO )   
    REFERENCES VEHICULO( ID_VEHICULO  );
GO


ALTER TABLE VENTA_ACCESORIO ADD        
	CONSTRAINT FK_SUCURSAL_VENTA_ACCESORIO
	FOREIGN KEY ( FK_DISTRIBUIDORA )   
    REFERENCES DISTRIBUIDOR_O_SUCURSAL( ID_SUCURSAL  );
GO

ALTER TABLE VENTA_ACCESORIO ADD        
	CONSTRAINT FK_CLIENTE_VENTA_ACCESORIO
	FOREIGN KEY ( FK_CLIENTE )   
    REFERENCES CLIENTE( ID_CLIENTE  );
GO


ALTER TABLE FACT_SERVICIO ADD        
	CONSTRAINT FK_SUCURSAL_FACT_SERVICIO
	FOREIGN KEY ( FK_DISTRIBUIDORA )   
    REFERENCES DISTRIBUIDOR_O_SUCURSAL( ID_SUCURSAL  );
GO
ALTER TABLE FACT_SERVICIO ADD        
	CONSTRAINT FK_CLIENTE_FACT_SERVICIO
	FOREIGN KEY ( FK_CLIENTE )   
    REFERENCES CLIENTE( ID_CLIENTE  );
GO





ALTER TABLE DET_FACT_SERVICIO ADD        
	CONSTRAINT DET_FACT_SERVICIO_SERVICIO
	FOREIGN KEY ( FK_SERVICIO )   
    REFERENCES SERVICIO( ID_SERVICIO  );
GO

ALTER TABLE DET_FACT_SERVICIO ADD        
	CONSTRAINT DET_FACT_SERVICIO_FACT_SERVICIO
	FOREIGN KEY ( FK_FACT_SERVICIO )   
    REFERENCES FACT_SERVICIO( ID_FACT_SERVICIO  );
GO






ALTER TABLE DET_VENTA_ACCESORIO ADD        
	CONSTRAINT DET_VENTA_ACCESORIO_ACCESORIO
	FOREIGN KEY ( FK_ACCESORIO )   
    REFERENCES ACCESORIO( ID_ACCESORIO  );
GO
ALTER TABLE DET_VENTA_ACCESORIO ADD        
	CONSTRAINT DET_VENTA_ACCESORIO_VENTA_ACCESORIO
	FOREIGN KEY ( FK_VENTA_ACCESORIO)   
    REFERENCES VENTA_ACCESORIO( ID_VENTA_ACCESORIO  );
GO







/*******************************RESTRICCION UNIQUE**************************/
/* 1.- La CURP debe ser unica en cada persona*/
ALTER TABLE CLIENTE
ADD CONSTRAINT UX_curp
UNIQUE NONCLUSTERED (CURP)
GO




/******************************1. Restricciones de dominio: DEFAULT*****************************/
/* 1.- valor por defecto para sexo es 'M' (masculino), 'F'(Femenino) insertarlo*/
CREATE DEFAULT df_sexo
AS 'M'
GO
EXEC sp_bindefault 'df_sexo', 'CLIENTE.SEXO'--variable sexo de persona, tome la variable df_sexo
GO

/* 2.- valor por defecto para municipio es Leon*/
CREATE DEFAULT df_ciudad
AS 'León'
GO
EXEC sp_bindefault 'df_ciudad', 'DISTRIBUIDOR_O_SUCURSAL.CIUDAD'
GO
EXEC sp_bindefault 'df_ciudad', 'ALMACEN_EMPRESA.CIUDAD'
GO

/*3.- valor por defecto para municipio es Guanajuato*/
CREATE DEFAULT df_estado
AS 'Guanajuato'
GO
EXEC sp_bindefault 'df_estado', 'DISTRIBUIDOR_O_SUCURSAL.estado'
GO
EXEC sp_bindefault 'df_estado', 'ALMACEN_EMPRESA.estado'
GO

/*4.- valor por defecto para las descripciones de las facturas y las ventas ex "Sin descripcion"*/
CREATE DEFAULT df_descripcion
AS 'Sin descripcion'
GO
EXEC sp_bindefault 'df_descripcion', 'FACTURA_ALMACEN.descripcion'
GO

/*5.- valor por defecto para el TIPO de un VEHICULO es "Eléctrico"*/
CREATE DEFAULT df_tipo_vehiculo
AS 'Eléctrico'
GO
EXEC sp_bindefault 'df_tipo_vehiculo', 'VEHICULO.tipo'
GO

/*5.- valor por defecto para el COLOR de un VEHICULO es "Eléctrico"*/
CREATE DEFAULT df_color_vehiculo
AS 'Grafito'
GO
EXEC sp_bindefault 'df_color_vehiculo', 'VEHICULO.color'
GO

/*6.- valor por defecto para el MODELO de un VEHICULO es "TSURU"*/
CREATE DEFAULT df_modelo_vehiculo
AS 'TSURU'
GO
EXEC sp_bindefault 'df_modelo_vehiculo', 'VEHICULO.modelo'
GO

/*7.- valor por defecto para la puntuacion de una SUCURSAL es 0*/
CREATE DEFAULT df_puntuacion_sucursal
AS 0
GO
EXEC sp_bindefault 'df_puntuacion_sucursal', 'DISTRIBUIDOR_O_SUCURSAL.puntuacion'
GO



/*************************************************2. RESTRICCIONES DE DOMINIO:  RULES****************/
/*  1- SOLAMENTE SE TIENEN LOS MODELOS DE COCHES MICRO,HIRAKI,
ALTIMA,APRIO,DATSUN,GT-R,LUCINO,MAXIMA,MICRA,NOTE,PLATINA,SENTRA,TIIDA,TSURU,VERSA*/	    
/*          
CREATE RULE RL_MODELOS_COCHES
AS 
@A_MODELOS IN ('MICRO','HIRAKI','ALTIMA','APRIO','DATSUN','GT-R','LUCINO','MAXIMA','MICRA',
'NOTE','PLATINA','SENTRA','TIIDA','TSURU','VERSA')
GO
EXEC SP_BINDRULE 'RL_MODELOS_COCHES','VEHICULO.MODELO'
--EXEC SP_UNBINDRULE 'RL_MODELOS_COCHES','VEHICULO.MODELO'
GO

*/



/*REGLA: solo admite en atributo sexo de la tabla persona M -> masculino  y una F- > femenino*/
create rule rl_sexo
as 
	@mivariable = 'M' or @mivariable ='F'
	--otra forma cuando son muchas @mivar IN('M','F')
Go 
EXEC sp_bindrule 'rl_sexo','CLIENTE.sexo'
go

create rule rl_cp
as --char (5)
	@cp LIKE('[0-9][0-9][0-9][0-9][0-9]')--Primer caracter es numero, el seguno igual, asi hasta el quinto
go
exec sp_bindrule 'rl_cp','DISTRIBUIDOR_O_SUCURSAL.cp'
exec sp_bindrule 'rl_cp','DISTRIBUIDOR_O_SUCURSAL.cp'
GO
/*
create DROP rule rl_curp as
--like compara cadenas
	@curp LIKE
	('[a-z][a-z][a-z][a-z][0-9][0-9][0-9][0-9][0-9][0-9][HM][a-z][a-z][a-z][a-z][a-z][0-9a-z][0-9]') OR
	@curp LIKE
	('[a-z][a-z][a-z][a-z][0-9][0-9][0-9][0-9][0-9][0-9][HM][a-z][a-z][a-z][a-z][a-z][0-9a-z][0-9a-z][0-9a-z]')
go
exec sp_bindrule 'rl_curp','CLIENTE.curp'
go
*/


/**************************************3. Restricciones de dominio: CHECK*********************/
ALTER TABLE DISTRIBUIDOR_O_SUCURSAL ADD CONSTRAINT CK_CIUDADES_ESTADOS
      CHECK( (CIUDAD IN ('ABASOLO','ACÁMBARO','SAN MIGUEL DE ALLENDE','APASEO EL ALTO','APASEO EL GRANDE',
				'ATARJEA','CELAYA','MANUEL DOBLADO','COMONFORT','CORONEO','CORTAZAR','CUERÁMARO','DOCTOR MORA',
				'DOLORES HIDALGO CUNA DE LA INDEPENDENCIA NACIONAL','GUANAJUATO','HUANÍMARO','IRAPUATO',
				'JARAL DEL PROGRESO','JERÉCUARO','LEON','MOROLEÓN','OCAMPO','PÉNJAMO','PUEBLO NUEVO','PURÍSIMA DEL RINCÓN',
				'ROMITA','SALAMANCA','SALVATIERRA','SAN DIEGO DE LA UNIÓN','SAN FELIPE','SAN FRANCISCO DEL RINCÓN',
				'SAN JOSÉ ITURBIDE','SAN LUIS DE LA PAZ','SANTA CATARINA','SANTA CRUZ DE JUVENTINO ROSAS',
				'SANTIAGO MARAVATÍO','SILAO','TARANDACUAO','TARIMORO','TIERRA BLANCA','URIANGATO',
				'VALLE DE SANTIAGO','VICTORIA','VILLAGRÁN','XICHÚ','YURIRIA') 
				AND Estado ='GUANAJUATO')  OR
			(CIUDAD IN ('AZCAPOTZALCO','COYOACAN','CUAJIMALPA DE MORELOS','GUSTAVO A. MADERO',
        		'IZTACALCO','IZTAPALAPA','LA MAGDALENA CONTRERAS','MILPA ALTA','ALVARO OBREGON',
        		'TLÁHUAC','TLALPAN','XOCHIMILCO','BENITO JUÁREZ','CUAUHTÉMOC','MIGUEL HIDALGO','VENUSTIANO CARRANZA')
				AND Estado ='Ciudad de Mexico')     OR
			(CIUDAD IN('ACAMBAY DE RUÍZ CASTAÑEDA','ACOLMAN','ACULCO','ALMOLOYA DE ALQUISIRAS','ALMOLOYA DE JUÁREZ',
				'ALMOLOYA DEL RÍO','AMANALCO','AMATEPEC','AMECAMECA','APAXCO','ATENCO','ATIZAPÁN','ATIZAPÁN DE ZARAGOZA',
				'ATLACOMULCO','ATLAUTLA','AXAPUSCO','AYAPANGO','CALIMAYA','CAPULHUAC','COACALCO DE BERRIOZÁBAL',
				'COATEPEC HARINAS','COCOTITLÁN','COYOTEPEC','CUAUTITLÁN','CHALCO','CHAPA DE MOTA','CHAPULTEPEC',
				'CHIAUTLA','CHICOLOAPAN','CHICONCUAC','CHIMALHUACÁN','DONATO GUERRA','ECATEPEC DE MORELOS','ECATZINGO',
				'HUEHUETOCA','HUEYPOXTLA','HUIXQUILUCAN','ISIDRO FABELA','IXTAPALUCA','IXTAPAN DE LA SAL','IXTAPAN DEL ORO',
				'IXTLAHUACA','XALATLACO','JALTENCO','JILOTEPEC','MORELOS')   
				AND Estado ='Estado de Mexico')
			)
GO

