/*DIMENSIONES VENTA ACCESORIOS*/

USE  Nissan
GO

--Vista para la sucursal
CREATE VIEW SucursalPPP_A
AS
SELECT ROW_NUMBER() OVER (ORDER BY ID_SUCURSAL) AS INDICE, ID_SUCURSAL 
 FROM Distribuidor_o_sucursal 
GO
 
SELECT * FROM SucursalPPP_A
GO

--Vista para los accesorios
CREATE VIEW AccesorioPPP_A
AS
SELECT ROW_NUMBER() OVER (ORDER BY ID_ACCESORIO) AS INDICE, ID_ACCESORIO
FROM ACCESORIO
GO

SELECT * FROM AccesorioPPP_A
GO

--Vista para el cliente
CREATE VIEW clientePPP_A
AS
SELECT ROW_NUMBER() OVER (ORDER BY ID_CLIENTE) AS INDICE, ID_CLIENTE 
 FROM CLIENTE 
GO

SELECT * FROM clientePPP_A
GO

CREATE VIEW VENTA_ACCESORIO_PPP_A
AS
SELECT ROW_NUMBER() OVER (ORDER BY ID_CLIENTE) AS INDICE, a.ID_ACCESORIO, s.ID_SUCURSAL, c.ID_CLIENTE, FECHA, ID_VENTA_ACCESORIO,DV.CANTIDAD FROM DISTRIBUIDOR_O_SUCURSAL AS s INNER JOIN VENTA_ACCESORIO va ON s.ID_SUCURSAL = va.FK_DISTRIBUIDORA
JOIN CLIENTE c ON c.ID_CLIENTE = va.FK_CLIENTE JOIN DET_VENTA_ACCESORIO dv ON dv.FK_VENTA_ACCESORIO = va.ID_VENTA_ACCESORIO JOIN ACCESORIO a ON dv.FK_ACCESORIO = a.ID_ACCESORIO
GO

SELECT * FROM VENTA_ACCESORIO_PPP_A
GO

CREATE TABLE TABLA_HECHOS_VENTA_ACCESORIO
(
ID_FECHA VARCHAR(15) NOT NULL,
ID_ACCESORIO VARCHAR (15) NOT NULL,
ID_SUCURSAL VARCHAR(15) NOT NULL,
ID_CLIENTE VARCHAR(15) NOT NULL,
NUM_VENTA VARCHAR (30) NOT NULL
)

CREATE TABLE DIMENSION_SUCURSAL_A(
    ID_SUCURSAL VARCHAR(15) NOT NULL,
	DESCRIPCION VARCHAR (300) NULL,
	ESTADO VARCHAR(30) NOT NULL ,
	CIUDAD VARCHAR (100) NOT NULL ,
	PUNTUACION INT NULL
); 


--SELECT * FROM ACCESORIO
CREATE TABLE DIMENSION_ACCESORIO_A (
	ID_ACCESORIO VARCHAR (15)  NOT NULL,
	DECRIPCION VARCHAR (200) NOT NULL,
	PRECIO MONEY NOT NULL, 
);
GO

CREATE TABLE DIMENSION_CLIENTE_A(
	ID_CLIENTE VARCHAR(15) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	PRIMER_APELLIDO VARCHAR(100) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(100) NULL,
	FECHA_NACIMIENTO DATE NULL,
	SEXO VARCHAR(1)
);
GO

CREATE TABLE DIMENSION_FECHA_A(
	ID_FECHA VARCHAR(15) NOT NULL ,
	DIA_DEL_MES INT NOT NULL,
	MES INT NOT NULL,
	AÑO INT NOT NULL,
	SEMANA_DEL_AÑO INT NOT NULL
);
GO

/****************************************************************************************************
ultima actualizacion: 09 DE SEPTIEBRE DE 2018 

RESTRICCIONES DE LLAVE PRIMARIA         PK                 *
*****************************************************************************************************/


ALTER TABLE DIMENSION_SUCURSAL_A  ADD 
	CONSTRAINT PK_SUCURSAL_DIMENSION_SUCURSAL_A 
	PRIMARY KEY  (ID_SUCURSAL); 
GO

ALTER TABLE DIMENSION_ACCESORIO_A  ADD 
	CONSTRAINT PK_ACCESORIO_DIMENSION_ACCESORIO_A
	PRIMARY KEY  (ID_ACCESORIO); 
GO
 

ALTER TABLE DIMENSION_CLIENTE_A  ADD 
	CONSTRAINT PK_DIMENSION_CLIENTE_A
	PRIMARY KEY  (ID_CLIENTE); 
GO

ALTER TABLE DIMENSION_FECHA_A  ADD 
	CONSTRAINT PK_FECHA_DIMENSION_FECHA_A
	PRIMARY KEY  (ID_FECHA); 
GO


/****************************************************************************************************
ultima actualizacion: 09 DE SEPTIEBRE DE 2018 
RESTRICCIONES DE LLAVE fORANEA         FK                 *
*****************************************************************************************************/


ALTER TABLE TABLA_HECHOS_VENTA_ACCESORIO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_ACCESORIO_DIMENSION_FECHA_a 
	FOREIGN KEY ( ID_FECHA )   
    REFERENCES DIMENSION_FECHA_A ( ID_FECHA  );
GO

ALTER TABLE TABLA_HECHOS_VENTA_ACCESORIO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_ACCESORIO_DIMENSION_ACCESORIO_A 
	FOREIGN KEY ( ID_ACCESORIO )   
    REFERENCES DIMENSION_ACCESORIO_A (ID_ACCESORIO);
GO

ALTER TABLE TABLA_HECHOS_VENTA_ACCESORIO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_ARTICULO_DIMENSION_SUCURSAL_A 
	FOREIGN KEY ( ID_SUCURSAL )   
    REFERENCES DIMENSION_SUCURSAL_A (ID_SUCURSAL);
GO

ALTER TABLE TABLA_HECHOS_VENTA_ACCESORIO ADD        
	CONSTRAINT TABLA_HECHO_VENTAS_ACCESORIO_DIMENSION_CLIENTE_A 
	FOREIGN KEY (ID_CLIENTE )   
    REFERENCES DIMENSION_CLIENTE_A (ID_CLIENTE);
GO

/*PROCEDIMIENTOS*/

/*DIMENSION ACCESORIO*/
CREATE PROC SP_LLENA_DIMENSION_ACCESORIO
  AS
     begin tran llena_dimension_accesorio
	 DECLARE  @ID_ACCESORIO VARCHAR (15) ,@DESCRIPCION VARCHAR (200) ,@PRECIO MONEY, @cantidad_accesorios BIGINT,
	 @CONT BIGINT=1, @CONT2 BIGINT = (SELECT COUNT(ID_ACCESORIO) FROM ACCESORIO)

	 WHILE(@CONT <=  @CONT2)
	 BEGIN
	 SELECT @ID_ACCESORIO = ID_ACCESORIO
		 FROM AccesorioPPP
		 WHERE INDICE = @CONT


	 SELECT @DESCRIPCION = DECRIPCION
		FROM ACCESORIO
		WHERE ID_ACCESORIO = @ID_ACCESORIO

     SELECT @PRECIO = PRECIO
		FROM ACCESORIO
		WHERE ID_ACCESORIO=@ID_ACCESORIO

	INSERT INTO DIMENSION_ACCESORIO_A VALUES (@ID_ACCESORIO,@DESCRIPCION, @PRECIO);
	
	SELECT * FROM DIMENSION_ACCESORIO_A

	 SET @CONT = @CONT + 1   
     END  -- FIN WHILE PRINC

	 IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_dimension_accesorio
   END
  ELSE  
    COMMIT TRAN llena_dimension_accesorio 
GO

--ejecucion
EXEC SP_LLENA_DIMENSION_ACCESORIO
GO
SELECT * FROM DIMENSION_ACCESORIO_A

/*DIMENSION CLIENTE*/

CREATE PROC SP_LLENA_DIMENSION_CLIENTE_A
  AS
     begin tran llena_dimension_cliente_A
	 DECLARE @ID_CLIENTE VARCHAR(15),  @NOMBRE VARCHAR(100),  @PRIMER_APELLIDO VARCHAR(100),  @SEGUNDO_APELLIDO VARCHAR(100), @FECHA_NACIMIENTO DATE, @SEXO VARCHAR(1),
	
      	
	 @CONT BIGINT = 1 , @CONT2 BIGINT=(SELECT COUNT(ID_CLIENTE) FROM CLIENTE)
	 
      
		
	 WHILE (@CONT <=  @CONT2)
        BEGIN 
           
	    SELECT  @ID_CLIENTE = ID_CLIENTE 
				FROM clientePPP_A
				WHERE INDICE = @CONT
				
				
		SELECT  @NOMBRE = NOMBRE 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
		SELECT  @PRIMER_APELLIDO = PRIMER_APELLIDO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
				SELECT  @SEGUNDO_APELLIDO = SEGUNDO_APELLIDO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
				SELECT  @FECHA_NACIMIENTO = FECHA_NACIMIENTO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
				SELECT  @SEXO = SEXO 
				FROM CLIENTE
				WHERE ID_CLIENTE = @ID_CLIENTE
				
		
				
				
				INSERT INTO DIMENSION_CLIENTE_A VALUES(@ID_CLIENTE,@NOMBRE,@PRIMER_APELLIDO,@SEGUNDO_APELLIDO,@FECHA_NACIMIENTO,@SEXO);
		
		
        SET @CONT = @CONT + 1   
     END  -- FIN WHILE PRINC
  IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_dimension_cliente_A 
   END
  ELSE  
    COMMIT TRAN llena_dimension_cliente_A   
GO

--ejecucion
EXEC SP_LLENA_DIMENSION_CLIENTE_A
SELECT * FROM DIMENSION_CLIENTE_A
GO

/*DIMENSION SUCURSAL*/
CREATE PROC SP_LLENA_DIMENSION_SUCURSAL_A
  AS
     begin tran llena_dimension_sucursal_A
	 DECLARE @ID_SUCURSAL VARCHAR(15),  @DESCRIPCION VARCHAR(300),  @ESTADO VARCHAR(30),  @CIUDAD VARCHAR(100), @PUNTUACION INT,
	
      	
	 @CONT BIGINT = 1 , @CONT2 BIGINT=(SELECT COUNT(ID_SUCURSAL) FROM DISTRIBUIDOR_O_SUCURSAL)
	 
      
		
	 WHILE (@CONT <=  @CONT2)
        BEGIN 
           
	    SELECT  @ID_SUCURSAL = ID_SUCURSAL 
				FROM SucursalPPP_A
				WHERE INDICE = @CONT
				
				
		SELECT  @DESCRIPCION = DESCRIPCION
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				
				SELECT  @ESTADO = ESTADO
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				
				SELECT  @CIUDAD = CIUDAD
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				
				SELECT  @PUNTUACION = PUNTUACION
				FROM DISTRIBUIDOR_O_SUCURSAL
				WHERE ID_SUCURSAL = @ID_SUCURSAL
				INSERT INTO DIMENSION_SUCURSAL_A VALUES(@ID_SUCURSAL,@DESCRIPCION,@ESTADO,@CIUDAD,@PUNTUACION);
		
		
        SET @CONT = @CONT + 1   
     END  -- FIN WHILE PRINC
  IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_dimension_sucursal_A 
   END
  ELSE  
    COMMIT TRAN llena_dimension_sucursal_A   
GO

--ejecucion
EXEC SP_LLENA_DIMENSION_SUCURSAL_A

SELECT * FROM DIMENSION_SUCURSAL_A


/*TABLA DE HECHOS*/
CREATE PROC  SP_LLENA_TABLA_HECHO_VENTAS_ACCESORIOS

  AS
     BEGIN TRAN llena_venta_accesorio
	 DECLARE @ID_FECHA VARCHAR(15), @ID_SUCURSAL VARCHAR(15),@ID_CLIENTE VARCHAR(15), @ID_ACCESORIO VARCHAR(15),@NUM_VENTA VARCHAR(30),@FECHA DATE,
	 @DIA_DEL_MES INT,@MES INT, @AÑO INT, @SEMANA_DEL_AÑO INT,
	 @CONT BIGINT = 1,  @N BIGINT=(SELECT COUNT(INDICE) FROM VENTA_ACCESORIO_PPP_A)

	 WHILE (@CONT <=  @N)
        BEGIN    
        SELECT @ID_SUCURSAL = ID_SUCURSAL 
				FROM VENTA_ACCESORIO_PPP_A
				WHERE INDICE = @CONT

				
				SELECT  @ID_ACCESORIO = ID_ACCESORIO
				FROM VENTA_ACCESORIO_PPP_A
				WHERE INDICE = @CONT

				SELECT  @ID_CLIENTE = ID_CLIENTE 
				FROM VENTA_ACCESORIO_PPP_A
				WHERE INDICE = @CONT
				
				SELECT  @NUM_VENTA = ID_VENTA_ACCESORIO
				FROM VENTA_ACCESORIO_PPP_A
				WHERE INDICE = @CONT

				SELECT  @FECHA = FECHA 
				FROM VENTA_ACCESORIO_PPP_A
				WHERE INDICE = @CONT

				SET @ID_FECHA= 'FEC' + CONVERT(VARCHAR,@CONT)
				SET @SEMANA_DEL_AÑO=DATEPART (ISO_WEEK,@FECHA)
					SET @DIA_DEL_MES=DATEPART (DAY,@FECHA)
					SET @MES=DATEPART (MONTH,@FECHA)
					SET @AÑO=DATEPART (YEAR,@FECHA)
				
				INSERT INTO DIMENSION_FECHA_A VALUES(@ID_FECHA,@DIA_DEL_MES,@MES,@AÑO,@SEMANA_DEL_AÑO)

				INSERT INTO TABLA_HECHOS_VENTA_ACCESORIO VALUES (@ID_FECHA,@ID_ACCESORIO,@ID_SUCURSAL,@ID_CLIENTE,@NUM_VENTA)
				
				
				SET @CONT = @CONT + 1   
        
     END  -- FIN WHILE PRINC
  IF @@ERROR <> 0
   BEGIN
      RAISERROR(N'MENSAJE', 16, 1);
     PRINT N'Error = ' + CAST(@@ERROR AS NVARCHAR(8));
     ROLLBACK TRAN llena_venta_accesorio
   END
  ELSE  
    COMMIT TRAN llena_venta_accesorio  
GO
 
EXEC SP_LLENA_TABLA_HECHO_VENTAS_ACCESORIOS
GO

SELECT * FROM TABLA_HECHOS_VENTA_ACCESORIO
	






